spring:
  application:
    name: service-example

#Sirve para mapear el dominio de la pc a localhost. Si no aparece una url fea, pero igual anda.
#eureka:
#  instance:
#    hostname: localhost
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
